services:
  - type: web
    name: skeleton-trending-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: COMMUNITY_GROUP_LINK
        value: https://t.me/YourCommunityGroup
      - key: NFT_MINTING_GROUP_LINK
        value: https://t.me/YourNFTGroup
      - key: PROMOTION_GROUP_LINK
        value: https://t.me/YourPromotionGroup
      - key: VERIFY_TREND_LINK
        value: https://t.me/skeletontrend
      - key: LOUNGE_GROUP_LINK
        value: https://t.me/skeletonlounge
      - key: SUPPORT_CONTACT
        value: @skeletondev
      - key: SOL_WALLET
        value: YourSolanaWalletAddressHere
      - key: ETH_WALLET
        value: 0xYourEthereumWalletAddressHere
      - key: BSC_WALLET
        value: 0xYourBSCWalletAddressHere
      - key: BASE_WALLET
        value: 0xYourBaseWalletAddressHere
      - key: PUMPFUN_WALLET
        value: YourSolanaWalletAddressHere
      - key: POSSUM_WALLET
        value: YourSolanaWalletAddressHere
      - key: FOURMEME_WALLET
        value: 0xYourBSCWalletAddressHere
